adjetivos = {
    'fiel': 1,
    'melhor filme': 3,
    'legal': 1, 'legalzinho': 1,
    'excelente': 3, 'excelentes': 3,
    'ótimo': 2, 'otimo': 2, 'ótima': 2, 'otima': 2, 'ótimos': 2, 'otimos': 2, 'ótimas': 2, 'otimas': 2,
    'bom': 1, 'boa': 1, 'bons': 1, 'boas': 1,
    'muito bom': 2, 'muito boa': 2, 'muito bons': 2, 'muito boas': 2,
    'maravilhoso': 3, 'maravilhosa': 3, 'maravilhosos': 3, 'maravilhosas': 3,
    'fantástico': 3, 'fantástica': 3, 'fantásticos': 3, 'fantásticas': 3,
    'incrível': 3, 'incríveis': 3,
    'positivo': 2, 'positiva': 2, 'positivos': 2, 'positivas': 2,
    'satisfatório': 1, 'satisfatória': 1, 'satisfatórios': 1, 'satisfatórias': 1,
    'adequado': 1, 'adequada': 1, 'adequados': 1, 'adequadas': 1,
    'agradável': 2, 'agradáveis': 2, 'promissor': 2, 'promissora': 2, 'promissores': 2, 'promissoras': 2,
    'encantador': 2, 'encantadora': 2, 'encantadores': 2, 'encantadoras': 2,
    'brilhante': 3, 'brilhantes': 3,
    'espetacular': 3, 'espetaculares': 3,
    'surpreendente': 3, 'surpreendentes': 3,
    'nota 10': 3, 'notas 10': 3,
    'superior': 2, 'superiores': 2,
    'interessante': 1, 'interessantes': 1,
    'divertido': 2, 'divertida ': 3,
    'gostar': 2, 'gostei': 2,
    'obra prima': 3, 'obra-prima': 3,
    'deslumbrante': 3, 'deslumbrantes': 3,
    'emocionante': 3, 'emocionantes': 3,
    'único': 2, 'única': 2, 'únicos': 2, 'únicas': 2,
    'magnífico': 3, 'magnífica': 3, 'magníficos': 3, 'magníficas': 3,
    'excepcional': 3, 'excepcionalmente': 3,
    'extraordinário': 3, 'extraordinária': 3, 'extraordinários': 3, 'extraordinárias': 3,
    'sensacional': 3, 'sensacionais': 3,
    'inconteste': 3, 'incontestes': 3,
    'irresistível': 3, 'irresistíveis': 3,
    'imprescindível': 3, 'imprescindíveis': 3,
    'extraordinário': 3, 'extraordinária': 3,
    'admirável': 3, 'admiráveis': 3,
    'perfeito': 3, 'perfeita': 3, 'perfeitos': 3, 'perfeitas': 3,
    'fenomenal': 3, 'fenomenais': 3,
    'impecável': 3, 'impecáveis': 3,
    'primoroso': 3, 'primorosa': 3, 'primorosos': 3, 'primorosas': 3,
    'top': 3, 'tops': 3,
    'glorioso': 3, 'gloriosa': 3, 'gloriosos': 3, 'gloriosas': 3,
    'formidável': 3, 'formidáveis': 3,
    'irretocável': 3, 'irretocáveis': 3,
    'magistral': 3, 'magistrais': 3,
    'cativante': 3, 'cativantes': 3,

    'porcaria': -3,
    'descaso': -1,
    'genérico': -1,
    'forçado': -1, 'forcado': -1,
    'bobo': -1, 'bobinho': -1,
    'lixo': -3,
    'decepcionante': -2,
    'ruim': -1, 'ruins': -1,
    'insuficiente': -2, 'insuficientes': -2,
    'desagradável': -2, 'desagradáveis': -2,
    'fraco': -2, 'fraca': -2, 'fracos': -2, 'fracas': -2,
    'pobre': -2, 'pobres': -2,
    'deficiente': -2, 'deficientes': -2,
    'falho': -2, 'falha': -2, 'falhos': -2, 'falhas': -2,
    'baixo': -1, 'baixa': -1, 'baixos': -1, 'baixas': -1,
    'inadequado': -1, 'inadequada': -1, 'inadequados': -1, 'inadequadas': -1,
    'desastroso': -3, 'desastrosa': -3, 'desastrosos': -3, 'desastrosas': -3,
    'péssimo': -3, 'péssima': -3, 'péssimos': -3, 'péssimas': -3,
    'horrível': -3, 'horríveis': -3,
    'terrível': -3, 'teríveis': -3,
    'lamentável': -3, 'lamentáveis': -3,
    'deplorável': -3, 'deploráveis': -3,
    'desastroso': -3, 'desastrosa': -3, 'desastrosos': -3, 'desastrosas': -3,
    'ruim demais': -3, 'pior': -3, 'piores': -3,
    'catastrófico': -3, 'catastrófica': -3, 'catastróficos': -3, 'catastróficas': -3,
    'desagradável': -2, 'desagradáveis': -2,
    'mediocre': -2, 'mediocres': -2,
    'desapontante': -2, 'desapontantes': -2,
    'furo no roteiro': -2, 'furos no roteiro': -2,  'tem furo no roteiro': -2, 'tem furos no roteiro': -2,  
    'detestável': -3, 'detestáveis': -3,
    'horrível de assistir': -3, 
    'insuportável': -3, 
    'nojeira': -3,
    'gambiarra': -2, 
    'farsa': -3,
    'esculacho': -3, 
    'chato': -2, 'chata': -2, 'chatos': -2, 'chatas': -2, 
    'tosco': -2, 'tosca': -2, 'toscos': -2, 'toscas': -2, 
    'ridículo': -2, 'ridícula': -2, 'ridículos': -2, 'ridículas': -2,
    'merda': -3,
    'bosta': -3,
}

adverbios = {
    'não': -1,
    'nem': -1,
    'jamais': -1,
    'nunca': -1,
    'pouco': 0.5,
    'muito': 2, 
    'demais': 2, 
    'extremamente': 3, 
    'altamente': 3, 
    'incrivelmente': 3, 
    'super': 3, 
    'bastante': 2, 
    'totalmente': 3, 
    'completamente': 3, 
    'absurdamente': 3, 
    'absolutamente': 3, 
    'imensamente': 3, 
    'tão': 2, 
    'bastante': 2, 
    'intensamente': 3, 
    'enormemente': 3, 
    'excessivamente': 3, 
    'maravilhosamente': 3, 
    'surpreendentemente': 3, 
    'irresistivelmente': 3, 
    'totalmente': 3
}

