adjetivos = {
    'excelente': +3, 'excelentes': +3,
    'ótimo': +2, 'otimo': +2, 'ótima': +2, 'otima': +2, 'ótimos': +2, 'otimos': +2, 'ótimas': +2, 'otimas': +2,
    'bom': +1, 'boa': +1, 'bons': +1, 'boas': +1,
    'muito bom': +2, 'muito boa': +2, 'muito bons': +2, 'muito boas': +2,
    'maravilhoso': +3, 'maravilhosa': +3, 'maravilhosos': +3, 'maravilhosas': +3,
    'fantástico': +3, 'fantástica': +3, 'fantásticos': +3, 'fantásticas': +3,
    'incrível': +3, 'incríveis': +3,
    'positivo': +2, 'positiva': +2, 'positivos': +2, 'positivas': +2,
    'satisfatório': +1, 'satisfatória': +1, 'satisfatórios': +1, 'satisfatórias': +1,
    'adequado': +1, 'adequada': +1, 'adequados': +1, 'adequadas': +1,
    'agradável': +2, 'agradáveis': +2, 'promissor': +2, 'promissora': +2, 'promissores': +2, 'promissoras': +2,
    'encantador': +2, 'encantadora': +2, 'encantadores': +2, 'encantadoras': +2,
    'brilhante': +3, 'brilhantes': +3,
    'espetacular': +3, 'espetaculares': +3,
    'surpreendente': +3, 'surpreendentes': +3,
    'nota 10': +3, 'notas 10': +3,
    'superior': +2, 'superiores': +2,

    'regular': 0, 'regulares': 0,
    'neutro': 0, 'neutra': 0, 'neutros': 0, 'neutras': 0,
    'mediano': 0, 'mediana': 0, 'medianos': 0, 'medianas': 0,

    'ruim': -1, 'ruins': -1,
    'insuficiente': -2, 'insuficientes': -2,
    'desagradável': -2, 'desagradáveis': -2,
    'fraco': -2, 'fraca': -2, 'fracos': -2, 'fracas': -2,
    'pobre': -2, 'pobres': -2,
    'deficiente': -2, 'deficientes': -2,
    'falho': -2, 'falha': -2, 'falhos': -2, 'falhas': -2,
    'baixo': -1, 'baixa': -1, 'baixos': -1, 'baixas': -1,
    'inadequado': -1, 'inadequada': -1, 'inadequados': -1, 'inadequadas': -1,
    'desastroso': -3, 'desastrosa': -3, 'desastrosos': -3, 'desastrosas': -3,
    'péssimo': -3, 'péssima': -3, 'péssimos': -3, 'péssimas': -3,
    'horrível': -3, 'horríveis': -3,
    'terrível': -3, 'teríveis': -3,
    'lamentável': -3, 'lamentáveis': -3,
    'deplorável': -3, 'deploráveis': -3,
    'desastroso': -3, 'desastrosa': -3, 'desastrosos': -3, 'desastrosas': -3,
    'ruim demais': -3, 'pior': -3, 'piores': -3,
    'catastrófico': -3, 'catastrófica': -3, 'catastróficos': -3, 'catastróficas': -3,
    'desagradável': -2, 'desagradáveis': -2,
    'mediocre': -2, 'mediocres': -2,
    'desapontante': -2, 'desapontantes': -2,
}

adverbios = {
    'muito': +2, 
    'demais': +2, 
    'extremamente': +3, 
    'altamente': +3, 
    'incrivelmente': +3, 
    'super': +3, 
    'bastante': +2, 
    'totalmente': +3, 
    'completamente': +3, 
    'absurdamente': +3, 
    'absolutamente': +3, 
    'imensamente': +3, 
    'tão': +2, 
    'bastante': +2, 
    'intensamente': +3, 
    'enormemente': +3, 
    'excessivamente': +3, 
    'maravilhosamente': +3, 
    'surpreendentemente': +3, 
    'irresistivelmente': +3, 
    'totalmente': +3
}

